# Generated by Django 4.2.23 on 2025-06-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_subscription_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0712345678', max_length=15),
        ),
    ]
